from application import db, create_app
from application.models.models import User, Album, BucketList, Content, Itinerary, PackingList, Preference, Token

app = create_app()

def delete_database():
    with app.app_context():
        db.drop_all()


def create_database():
    with app.app_context():
        db.create_all()


def add_entries():
    user1 = User(first_name="Sarah", last_name="Soutoul", email="sarah.soutoul@getfutureproof.co.uk", username="sarah", password="$2b$10$1GieRj2Com/Uw6c/Zp5UOe6EMbX5n6Fi5V3XXm0ZHtB9CZqk3fX2", profile_pic="https://ca.slack-edge.com/THYP60S66-U03D8LYE7B7-7f35f18585a0-512")
    user2 = User(first_name="Monia", last_name="Favaro", email="monia@getfutureproof.co.uk", username="monia", password="$2b$10$1GieRj2Com/Uw6c/Zp5UOedNY0MdYYtFbZMj96CVxKQg0JAd0u6YG", profile_pic="https://ca.slack-edge.com/THYP60S66-U03197WD88Z-511a888c6308-512")
    user3 = User(first_name="Tom", last_name="Byrne", email="tom.byrne@getfutureproof.co.uk", username="tom", password="$2b$10$1GieRj2Com/Uw6c/Zp5UOe33hy93eiLPMh9lszzyGK95nPxVHa12y", profile_pic="https://ca.slack-edge.com/THYP60S66-U03NWUXUDEZ-7f3b0d50f881-512")
    user4 = User(first_name="Simon", last_name="Clemson", email="simon.clemson@getfutureproof.co.uk", username="simon", password="$2b$10$1GieRj2Com/Uw6c/Zp5UOeo4NPX3d3HoQoggArWIEfKzFX4oEh.u6", profile_pic="https://ca.slack-edge.com/THYP60S66-U03DQ71GXED-f8bd8ddfff2e-512")

    preference1 = Preference(foods="", hobbies="hiking, football", other="", user_id=1)
    preference2 = Preference(foods="vegan", hobbies="", other="", user_id=2)
    preference3 = Preference(foods="italian", hobbies="", other="", user_id=3)
    preference4 = Preference(foods="", hobbies="football", other="", user_id=4)

    packinglist1 = PackingList( items="clothing", item_status =False, user_id=1)
    packinglist2 = PackingList( items="toiletries", item_status =False, user_id=1)
    packinglist3 = PackingList( items="phone", item_status =False,user_id=1)
    packinglist4 = PackingList( items="passport", item_status =False, user_id=1)
    packinglist5 = PackingList( items="wallet", item_status =False,user_id=1)
    packinglist6 = PackingList( items="phone", item_status =False,user_id=2)
    packinglist7 = PackingList( items="wallet", item_status =False,user_id=2)
    packinglist8 = PackingList( items="keys", item_status =False,user_id=2)
    packinglist9 = PackingList( items="clothing", item_status =False,user_id=3)
    packinglist10 = PackingList( items="toiletries", item_status =False,user_id=3)
    packinglist11 = PackingList( items="phone", item_status =False,user_id=3)
    packinglist12 = PackingList( items="passport", item_status =False,user_id=3)
    packinglist13 = PackingList( items="wallet", item_status =False,user_id=3)
    packinglist14 = PackingList(items="wallet", item_status =False,user_id=4)
    packinglist15 = PackingList( items="phone", item_status =False,user_id=4)
    packinglist16 = PackingList( items="cash", item_status =False,user_id=4)
    packinglist17 = PackingList( items="tickets", item_status =False,user_id=4)
 

    album1 = Album(title="Trainer Trip", location="Tokyo", description="Nice relaxing holiday after a teaching the best cohort!", members="1,2,3,4", start_date="2023-08-19T08:00:00Z", end_date="2023-08-26T08:00:00Z", share_code=594652, cover_photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692271509/Aitenary-groupimage/mountains-in-japan-mt.-fuji-tokyo-1024x619_cy9lb8.webp", user_id=1)

    album2 = Album(title="Tropical Getaway", location="Brazil", description="Escape to the tropical paradise of Brazil with your travel mates and unwind after a long project!", members="2,3,4,5", start_date="2023-08-18T08:00:00Z", end_date="2023-08-25T08:00:00Z", share_code=492873, cover_photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692269637/Aitenary-groupimage/brazil_jtv4nj.jpg", user_id=1)
    album3 = Album(title="Enchanting Istanbul", location="Istanbul", description="Experience the enchanting beauty of Istanbul's rich history, vibrant markets, and stunning architecture!", members="2,3,4,5", start_date="2023-08-18T08:00:00Z", end_date="2023-08-25T08:00:00Z", share_code=761502, cover_photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692269637/Aitenary-groupimage/istanbul_rvaffo.jpg", user_id=1)
    album4 = Album(title="Sarah's hendo", location="", description="Sarah's hendo party", members="2,3,4,5", start_date="2023-08-18T08:00:00Z", end_date="2023-08-25T08:00:00Z", share_code=238964, cover_photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692269635/Aitenary-groupimage/sarahshendo_jgzxp2.jpg", user_id=1)
    album5 = Album(title="Mystical Morocco", location="Morocco", description="Immerse yourself in the mystical allure of Morocco's colorful markets, desert landscapes, and ancient cities!", members="2,3,4,5", start_date="2023-08-18T08:00:00Z", end_date="2023-08-25T08:00:00Z", share_code=605719, cover_photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692269636/Aitenary-groupimage/morocco_jcjiyo.jpg", user_id=1)
    album6 = Album(title="Coastal Croatia", location="Croatia", description="Discover the stunning coastal beauty and charming towns of Croatia while creating unforgettable memories!", members="2,3,4,5", start_date="2023-08-18T08:00:00Z", end_date="2023-08-25T08:00:00Z", share_code=819356, cover_photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692269636/Aitenary-groupimage/croatia_pyfgjs.jpg", user_id=1)

    content1 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266776/Final-project-tokyo/c0107188-800px-wm_jhjvu7.jpg", description="Tokyo Metropolitan Views", tags="", album_id=1)
    content2 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266776/Final-project-tokyo/img_0_fmukfd_a0n2yy.jpg", description="Tokyo Metropolitan Views", tags="", album_id=1)
    content3 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266778/Final-project-tokyo/photo-1547448526-5e9d57fa28f7_p0u4qg.jpg", description="Shibuya Crossing", tags="", album_id=1)
    content4 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266776/Final-project-tokyo/c0107188-800px-wm_jhjvu7.jpg", description="Lights!", tags="", album_id=1)
    content5 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266779/Final-project-tokyo/7869b2f6d8e68e89909201dfcc4c67869b2_duwec6.jpg", description="I took this one after Simon got lost in the gardens", tags="", album_id=1)
    content6 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266779/Final-project-tokyo/300721wkAFTER-ROBOT-CAFEphoto06_deqayn.jpg", description="ChatGPT Version 5", tags="", album_id=1)
    content7 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266779/Final-project-tokyo/4327156_m-1200x802_izbaol.jpg", description="Wasabi Icecream", tags="", album_id=1)
    content8 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266778/Final-project-tokyo/tsukiji-outer-market-tourists-adriana-paradiso-770x578_asnnnl.jpg", description="The smelly markets", tags="", album_id=1)
    content9 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266778/Final-project-tokyo/shibuya_gljt5w.jpg", description="Winner!", tags="", album_id=1)
    content10 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266777/Final-project-tokyo/snow-monkey_aycrh2.webp", description="Cute lil monkeys that really took a liking to Tom", tags="", album_id=1)
    content11 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266777/Final-project-tokyo/2080_05_z3u1hj.jpg", description="Favorite bit of the trip", tags="", album_id=1)
    content12 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266775/Final-project-tokyo/kanagawa-black-eggs-of-owakudani-hakone-198676_c99dug.jpg", description="Gross black eggs", tags="", album_id=1)
    content13 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266777/Final-project-tokyo/shutterstock_774407953_s8frsu.jpg", description="", tags="", album_id=1)
    content14 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266776/Final-project-tokyo/Sushi-Saito-Inside_jjatzu.jpg", description="Tom got over his seafood trauma eventually", tags="", album_id=1)
    content15 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266776/Final-project-tokyo/Sybilla-Patrizia-5_g3ivdi.jpg", description="Hedgehogs", tags="", album_id=1)
    content16 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266775/Final-project-tokyo/IMG_20171211_212623-1024x768_vnsex5.png", description="Worst dish of the trip 0/10 do not recommend", tags="", album_id=1)
    content17 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266775/Final-project-tokyo/p00xftgs_itznh8.jpg", description="Pachinkko", tags="", album_id=1)
    content18 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266774/Final-project-tokyo/image_pr4pua.png", description="I could eat this all day", tags="", album_id=1)
    content19 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266776/Final-project-tokyo/sabukaru-online-magazine-graffitti-in-tokyo-japanesestreetart-tags-murals-legal-illegal-spray-streetculture10_fyiqup.webp", description="", tags="", album_id=1)
    content20 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266775/Final-project-tokyo/IMG_20171211_202055-1024x768_zuk56m.png", description="The millioneth ramen", tags="", album_id=1)
    content21 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266774/Final-project-tokyo/hama-rikyu-gardens-feature_fsf4do.webp", description="", tags="", album_id=1)
    content22 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266774/Final-project-tokyo/Kaiseiyu-Aquarium-where-carp-swims_ijjvif.jpg", description="Onsen", tags="", album_id=1)
    content23 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266774/Final-project-tokyo/IMG_20171211_193651-1024x768_hzn4c3.png", description="Fugu", tags="", album_id=1)
    content24 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266773/Final-project-tokyo/DSC06507_mini_qmuf9x.jpg", description="Monia giving it some beans in karaoke", tags="", album_id=1)
    content25 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266774/Final-project-tokyo/IMG_0535_vip90j.jpg", description="", tags="", album_id=1)
    content26 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266774/Final-project-tokyo/istockphoto-526845820-612x612_vmlxq0.jpg", description="Tokyo Tower", tags="", album_id=1)
    content27 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266773/Final-project-tokyo/images_o8o5ch.jpg", description="Group pic", tags="", album_id=1)
    content28 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266773/Final-project-tokyo/gachi_abura_ramen_adriana_0_ruq1z6.jpg", description="Best ramen of the trip 11/10", tags="", album_id=1)
    content29 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266773/Final-project-tokyo/2061120822_221c6902f2_c_nejimz.jpg", description="Last day :(", tags="", album_id=1)
    content30 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266772/Final-project-tokyo/cat-cafes-tokyo-japan-2_yi7gyu.jpg", description="Monia's in heaven", tags="", album_id=1)
    content31 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266772/Final-project-tokyo/20190826093944_905816524_10037_0_xxcpmf.jpg", description="", tags="", album_id=1)
    content32 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266772/Final-project-tokyo/batting-a-great-way-to_oteewb.jpg", description="Simon didnt manage to hit one!", tags="", album_id=1)
    content33 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266772/Final-project-tokyo/download_b5j53x.jpg", description="Octopuus Balls", tags="", album_id=1)
    content34 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266772/Final-project-tokyo/area002_0986_27_nd3rbr.jpg", description="", tags="", album_id=1)
    content35 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266772/Final-project-tokyo/20161020-Ichiran-12.0.0_lkwl9o.jpg", description="", tags="", album_id=1)
    content36 = Content(photo="https://res.cloudinary.com/dwxery2ci/image/upload/v1692266772/Final-project-tokyo/1370256021092_pme0ux.jpg", description="", tags="", album_id=1)
    content37 = Content(photo="", description="Tom accidentally mistook wasabi for avocado at a sushi restaurant and ended up with tears streaming down his face!", tags="", album_id=1)
    content38 = Content(photo="", description="Monia tried to speak some Japanese to a local shopkeeper but ended up saying 'I have a big cow' instead of 'I want a big bag.'", tags="", album_id=1)
    content39 = Content(photo="", description="Simon got trapped in a traditional Japanese sliding door and had to be rescued by the staff while everyone watched!", tags="", album_id=1)
    content40 = Content(photo="", description="Sarah attempted to use chopsticks like a pro, but her attempt resulted in launching a piece of sushi across the table and hitting an old lady.", tags="", album_id=1)
    content41 = Content(photo="", description="Tom confidently ordered a dish that turned out to be poisonous puffer fish", tags="", album_id=1)
    content42 = Content(photo="", description="Monia tried to mimic the graceful bowing of the locals but ended up stumbling and almost falling over", tags="", album_id=1)
    content43 = Content(photo="", description="Simon attempted to take a selfie with a street performer and ended up as part of the act.", tags="", album_id=1)
    content44 = Content(photo="", description="Sarah joined a karaoke session and belted out a song so out of tune that we were asked to leave.", tags="", album_id=1)
    content45 = Content(photo="", description="Tom got caught in a sudden downpour and had to wear a kimono for the rest of the day", tags="", album_id=1)
    content46 = Content(photo="", description="Monia tried to use the automated toilet controls but got confused and pressed the wrong button, resulting in an embarrasing damp patch", tags="", album_id=1)
    content47 = Content(photo="", description="Simon got on the wrong tube and ended up on a bullet train to another city", tags="", album_id=1)
    content48 = Content(photo="", description="Sarah attempted to wear a kimono and got entangled in the intricate folds, requiring the help of three people to get her out of the predicament.", tags="", album_id=1)
    content49 = Content(photo="", description="Tom's attempt at speaking Japanese led to a hilarious misunderstanding, where he accidentally ordered two dozen eggs instead of two eggs for breakfast.", tags="", album_id=1)
    content50 = Content(photo="", description="Sarah was mistook a local for a celebrity and kept being asked for autographs.", tags="", album_id=1)
    content51 = Content(photo="", description="Simon got overly enthusiastic about trying street food and ended up eating something incredibly spicy and had to run in to a 7/11 to get some water.", tags="", album_id=1)



    with app.app_context():
        db.session.add(user1)
        db.session.add(user2)
        db.session.add(user3)
        db.session.add(user4)

        db.session.add(preference1)
        db.session.add(preference2)
        db.session.add(preference3)
        db.session.add(preference4)

        db.session.add(packinglist1)
        db.session.add(packinglist2)
        db.session.add(packinglist3)
        db.session.add(packinglist4)
        db.session.add(packinglist5)
        db.session.add(packinglist6)
        db.session.add(packinglist7)
        db.session.add(packinglist8)
        db.session.add(packinglist9)
        db.session.add(packinglist10)
        db.session.add(packinglist11)
        db.session.add(packinglist12)
        db.session.add(packinglist13)
        db.session.add(packinglist14)
        db.session.add(packinglist15)
        db.session.add(packinglist16)
        db.session.add(packinglist17)


        db.session.add(album1)
        db.session.add(album2)
        db.session.add(album3)
        db.session.add(album4)
        db.session.add(album5)

        db.session.add(content1)
        db.session.add(content2)
        db.session.add(content3)
        db.session.add(content4)
        db.session.add(content5)
        db.session.add(content6)
        db.session.add(content7)
        db.session.add(content8)
        db.session.add(content9)
        db.session.add(content10)
        db.session.add(content11)
        db.session.add(content12)
        db.session.add(content13)
        db.session.add(content14)
        db.session.add(content15)
        db.session.add(content16)
        db.session.add(content17)
        db.session.add(content18)
        db.session.add(content19)
        db.session.add(content20)
        db.session.add(content21)
        db.session.add(content22)
        db.session.add(content23)
        db.session.add(content24)
        db.session.add(content25)
        db.session.add(content26)
        db.session.add(content27)
        db.session.add(content28)
        db.session.add(content29)
        db.session.add(content30)
        db.session.add(content31)
        db.session.add(content32)
        db.session.add(content33)
        db.session.add(content34)
        db.session.add(content35)
        db.session.add(content36)
        db.session.add(content37)
        db.session.add(content38)
        db.session.add(content39)
        db.session.add(content40)
        db.session.add(content41)
        db.session.add(content42)
        db.session.add(content43)
        db.session.add(content44)
        db.session.add(content45)
        db.session.add(content46)
        db.session.add(content47)
        db.session.add(content48)
        db.session.add(content49)
        db.session.add(content50)
        db.session.add(content51)

        db.session.commit()


if __name__ == "__main__":
    delete_database()
    create_database()
    add_entries()
